<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>9e5395a6-9832-4dcb-b06c-4db5032992f0</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.powr.io/plugins/popup/cached_view?load=async&amp;index=1&amp;unique_label=&amp;powr_token=zzzlkjsf94r2&amp;user_label=Label&amp;demo_mode=true&amp;template_powr_token=&amp;color=rgb(102%2C%20102%2C%20102)&amp;backgroundColor=rgb(255%2C%20255%2C%20255)&amp;fontFamily=Roboto%2C%20sans-serif</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>powrindex</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>595px</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app_details-show&quot;)/div[@class=&quot;site-wrapper&quot;]/div[@class=&quot;new-lander scheme-3&quot;]/section[@class=&quot;bg2 text-center&quot;]/div[@class=&quot;row container liveDemoContainer demo_on_below&quot;]/div[@class=&quot;powr-popup powrLoaded&quot;]/iframe[1]</value>
   </webElementProperties>
</WebElementEntity>
