WebUI.comment('Feature: Customer Login')
WebUI.comment('  As a mobile customer of digiSG, I want to Login, so that I can see my banking profile.')
WebUI.comment('  ')
WebUI.comment('  Scenario: Invalid Customer Login')
WebUI.comment('    Given invalid username and password on mobile app')
WebUI.comment('    When the username phrase \"test\" and password phrase \"123456\" are entered')
WebUI.comment('    Then results for customer \"test\" are shown as failed with \"invalid username/password details\" error message')
