<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DigiBankIN_Web_Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-06-01T15:37:17</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>1b2ea143-ff7e-4b76-bdeb-47eb9e8598e8</testSuiteGuid>
   <testCaseLink>
      <guid>58b1a5f0-9f00-4ffd-a971-3c01be465aa7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Web/DigiBankIN_Login_TC001_BlankUserName_ErrorValidation</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24e6fe0e-d367-454a-9f49-0f7cb39dac07</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91962c3c-6646-43ff-972e-96d1376a8dcc</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
